# Generated by Django 6.0.3 on 2026-03-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('resume_submitted', 'Resume Submitted'), ('interview_scheduled', 'Interview Scheduled'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected')], default='resume_submitted', max_length=30)),
                ('work_type', models.CharField(blank=True, choices=[('on_site', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=10)),
                ('source', models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('company_website', 'Company Website'), ('referral', 'Referral'), ('recruiter', 'Recruiter'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('office_location', models.CharField(blank=True, max_length=200)),
                ('key_contacts', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
