# Generated by Django 6.0.3 on 2026-03-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_status_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('exploring', 'Exploring'), ('resume_submitted', 'Resume Submitted'), ('interview_scheduled', 'Interview Scheduled'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected')], default='resume_submitted', max_length=30),
        ),
    ]
