# Generated by Django 6.0.3 on 2026-03-23 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0002_job_application_status_url_alter_job_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='jobtracker.job')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
